spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: testhee39@gmail.com
    password: sarilyenunlzojpt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password:
mybatis:
  type-aliases-package: com.example.project.vo
  mapper-locations: mapper/*.xml
custom:
  siteName: gachapong
  siteMainUri: http://localhost:8080
  emailFrom: no-reply@localhost
  emailFromName: gachapong
file:
  dir: /Users/babydoll/Documents/upload
gacha:
  dir: /Users/babydoll/Documents/gacha